# Generated by Django 5.1.7 on 2025-10-05 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CC', '0003_bookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instituteinfo',
            name='nearby_hostels',
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('distance_from_institute', models.CharField(help_text='e.g., 0.5 km, 10 min walk', max_length=100)),
                ('contact_info', models.TextField()),
                ('rent_range', models.CharField(help_text='e.g., ₹5000-₹8000/month', max_length=100)),
                ('amenities', models.TextField(help_text='Comma-separated amenities')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearby_hostels', to='CC.instituteinfo')),
            ],
            options={
                'verbose_name_plural': 'Hostels',
                'ordering': ['distance_from_institute'],
            },
        ),
        migrations.CreateModel(
            name='HostelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hostels/')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='CC.hostel')),
            ],
        ),
    ]
